directories:
  data_dir: "data"
  data_dir_euroleague_games: "data/euroleague_games"
  data_dir_euroleague_data: "data/euroleague_data"
  data_dir_datalog: "data/datalog.json"
  data_dir_features_data: "data/euroleague_features"
  data_dir_predictions: "data/euroleague_predictions"
  data_dir_optimizations: "data/euroleague_optimizations"
data_acquisition:
  competition_code: "E"
  season: 2024
feature_engineering:
  limit_up_to_week: 19
predictive_modeling:
  training_min_weeks: 5
  baseline_column_predictions: "valuation_expanding_mean_plr_tmpr"
  model_column_predictions: "valuation_pred"
  predictive_model_string: "LR"
  predictive_model_id_cols:
    - "week"
    - "slug"
    - "team_code"
  predictive_model_cats_cols:
    - "team_code"
    - "slug"
squad_optimization:
  optimization_solver: "appsi_highs"
  baseline_column_optimizations: "valuation_expanding_mean_plr_tmpr"
  model_column_optimizations: "valuation_pred"
  force_players: []