site_name: fun-euroleague-fantasy
repo_url: https://github.com/Takfes/fun-euroleague-fantasy
site_url: https://Takfes.github.io/fun-euroleague-fantasy
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Takfes
edit_uri: edit/main/docs/
repo_name: Takfes/fun-euroleague-fantasy
copyright: Maintained by <a href="https://Takfes.com">Takfes</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Takfes/fun-euroleague-fantasy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fun-euroleague-fantasy

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
